apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labeling-webhook
  template:
    metadata:
      labels:
        app: labeling-webhook
    spec:
      containers:
      - name: admission-webhook-container
        image: ghcr.io/dystewart/k8s-admission-controller/mutator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        volumeMounts:
          - name: certs
            mountPath: /etc/certs
      volumes:
      - name: certs
        secret:
          secretName: svc-cert

