apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
  - deployment.yaml
  - webhooks/mutatingWebhook.yaml
  - webhooks/validatingwebhook.yaml
  - service.yaml
  - statefulsets/sts-to-label.yaml
