apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: statefulset-labeling-webhook
webhooks:
- name: labeling.webhook.example.com
  clientConfig:
    service:
      name: labeling-webhook-service
      namespace: test
      path: "/"
  rules:
  - operations: ["CREATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["statefulsets"]
  sideEffects: None  # specify appropriate value, None or NoneOnDryRun
  admissionReviewVersions:
  - v1
