apiVersion: v1
kind: Service
metadata:
  name: labeling-webhook-service
  namespace: test
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: "svc-cert"
spec:
  selector:
    app: labeling-webhook
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
