apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  namespace: test
  name: validator
webhooks:
  - name: validating.webhook.example.com
    clientConfig:
      service:
        name: labeling-webhook-service
        namespace: test
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["statefulsets"]
    sideEffects: None
    admissionReviewVersions: ["v1"]